FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache \
  build-base \
  git \
  ruby-dev \
  ruby-bundler \
  # Required by activesupport
  ruby-json \
  sqlite-dev \
  # Timezone information
  tzdata \
  # For nokogiri gem
  zlib-dev

# Copy only files for bundle install first (layer does not change as often)
COPY Gemfile .
COPY Gemfile.lock .

RUN bundle install --jobs 4 --without development --no-cache \
# https://www.georg-ledermann.de/blog/2018/04/19/dockerize-rails-the-lean-way/
  && rm -rf vendor/bundle/cache/*.gem \
  && find vendor/bundle/gems/ -name "*.c" -delete || true \
  && find vendor/bundle/gems/ -name "*.o" -delete || true

COPY . .

ENV RAILS_ENV=test

RUN REQUIRE_MASTER_KEY=false SECRET_KEY_BASE=1 bundle exec rails db:migrate

CMD ["bundle", "exec", "rails", "test"]
