# TODO Do not use a separate dockerfile config. Perhaps extend base image instead.
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache \
  build-base \
  ruby-dev \
  ruby-bundler \
  # Required by activesupport
  ruby-json \
  sqlite-dev \
  # Timezone information
  tzdata \
  # For nokogiri gem
  zlib-dev

ADD https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 ./cc-test-reporter
RUN chmod +x ./cc-test-reporter

# Copy only files for bundle/yarn install first (layer does not change as often)
COPY Gemfile .
COPY Gemfile.lock .
COPY package.json .
COPY yarn.lock .

RUN bundle install --jobs 4 --without development --no-cache \
# https://www.georg-ledermann.de/blog/2018/04/19/dockerize-rails-the-lean-way/
  && rm -rf vendor/bundle/cache/*.gem \
  && find vendor/bundle/gems/ -name "*.c" -delete || true \
  && find vendor/bundle/gems/ -name "*.o" -delete || true

COPY . .

ENV RAILS_ENV=test

RUN REQUIRE_MASTER_KEY=false SECRET_KEY_BASE=1 bundle exec rails db:migrate

CMD ["bundle", "exec", "rails", "test"]
